apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  #nodePort: 6543
  selector:
    app: api
  ports:
  - name: "api"
    port: 31415
    targetPort: 31415
    nodePort: 31415
