apiVersion: v1
kind: Service
metadata:
  name: apiv2
spec:
  type: NodePort
  #nodePort: 6543
  selector:
    app: apiv2
  ports:
  - name: "apiv2"
    port: 31415
    targetPort: 31415
    nodePort: 31415
