apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
  - name: "9042"
    port: 9042
    targetPort: 9042
  - name: "9160"
    port: 9160
    targetPort: 9160
  - name: "7000"
    port: 7000
    targetPort: 7000
