apiVersion: v1
kind: Service
metadata:
  name: apiv2
spec:
  ports:
    - name: apiv2
      protocol: "TCP"
      port: 31415
  selector: {}
---

apiVersion: v1
kind: Service
metadata:
  name: lmtpd
spec:
  ports:
    - name: lmtpd
      protocol: "TCP"
      port: 2525
  selector: {}
---

kind: Endpoints
apiVersion: v1
metadata:
  name: apiv2
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 31415
        name: "apiv2"
---

kind: Endpoints
apiVersion: v1
metadata:
  name: lmtpd
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 2525
        name: "lmtpd"
