apiVersion: v1
metadata:
  name: apiv1
spec:
  ports:
    - name: apiv1
      protocol: "TCP"
      port: 6543
  selector: {}
---

kind: Endpoints
apiVersion: v1
metadata:
  name: apiv1
subsets: 
  - addresses:
      - ip: localhost
    ports:
      - port: 31415
        name: "apiv1"
