apiVersion: v1
kind: Service
metadata:
  name: apiv1
spec:
  ports:
    - name: apiv1
      protocol: "TCP"
      port: 6543
  selector: {}
---

kind: Endpoints
apiVersion: v1
metadata:
  name: apiv1
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 6543
        name: "apiv1"
