version: '2.1'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local

services:
  # Proxy API
  proxy-api:
    image: nginx
    links:
      - apiv2:apiv2
      - apiv1:apiv1
    ports:
      - "31415:31415"
    volumes:
      - ./conf/proxy-api.conf:/etc/nginx/nginx.conf
  # Caliopen APIv2
  apiv2:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-api
    image: caliopen_apiv2
    ## this very bad config for a public machine
    links:
      - redis:redis
      - cassandra:cassandra
      - elasticsearch:elasticsearch
      - nats:nats
      - object-store:minio
    ports:
      - "6544:6544"
    volumes:
      - ../src/backend/configs:/etc/caliopen
  # Caliopen APIv1
  apiv1:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.py-api
    image: caliopen_apiv1
    links:
      - redis:redis
      - cassandra:cassandra
      - elasticsearch:elasticsearch
    ports:
      - "6543:6543"
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    ports:
        - "6379:6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.cli
    image: caliopen_cli
    links:
      - cassandra:cassandra
      - elasticsearch:elasticsearch
      - lmtpd:lmtpd
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs:/etc/caliopen

  # Caliopen frontend
  frontend:
    build:
      context: ../src/frontend/web_application
    image: caliopen_frontend
    ports:
      - "4000:4000"
    links:
      - proxy-api:proxy-api
    environment:
      CALIOPEN_API_HOSTNAME: proxy-api

  # Broker
  lmtpd:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-lmtp
    image: caliopen_lmtpd
    links:
      - cassandra:cassandra
      - elasticsearch:elasticsearch
      - object-store:minio
      - nats:nats
      - inbucket:smtp
    ports:
      - "2525:2525"
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # NATS
  nats:
    image: nats:0.9.6
    ports:
      - "4222:4222"
      - "8222:8222"

  # NATS Message Handler
  mq_worker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.mq-worker
    image: caliopen_mq_worker
    links:
      - cassandra:cassandra
      - elasticsearch:elasticsearch
      - nats:nats
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # object storage
  object-store:
    image: minio/minio
    ports:
      - "9090:9090"
    volumes:
      - ../src/backend/configs/minio:/etc/caliopen/minio
      - store:/export
    command:
      server --address :9090 -C /etc/caliopen/minio /export
    environment:
      - MINIO_ACCESS_KEY=CALIOPEN_ACCESS_KEY_
      - MINIO_SECRET_KEY=CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD

  # Worker for remote identities
  imap_worker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.imap-worker
    image: caliopen_imap_worker
    links:
      - cassandra:cassandra
      - object-store:minio
      - elasticsearch:elasticsearch
      - nats:nats
    volumes:
      - ../src/backend/configs:/etc/caliopen

  twitter_worker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.twitter-worker
    image: caliopen_twitter_worker
    links:
    - cassandra:cassandra
    - object-store:minio
    - elasticsearch:elasticsearch
    - nats:nats
    volumes:
    - ../src/backend/configs:/etc/caliopen

  # Poller for remote identities
  identity_poller:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.identity-poller
    image: caliopen_identity_poller
    links:
      - imap_worker:imapworker
      - mq_worker:mqworker
      - nats:nats
      - twitter_worker:twitterworker
    volumes:
      - ../src/backend/configs:/etc/caliopen

  # Inbucket : a small smtp server to catch all outgoing emails for testing purpose
  # point your browser at localhost:8888
  inbucket:
    image: jhillyerd/inbucket
    ports:
      - "8888:9000"
      - "2500:2500"
