version: '2.1'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local
services:
  # Proxy API
  proxyapi:
    image: nginx
    depends_on:
      - apiv1
      - apiv2
    expose:
      - "31415"
    volumes:
      - ./conf/proxy-api.conf:/etc/nginx/nginx.conf
  # Caliopen APIv2
  apiv2:
    image: public-registry.caliopen.org/caliopen_apiv2:develop
    depends_on:
      - redis
      - cassandra
      - nats
      - elasticsearch
      - objectstore
    expose:
      - "6544"
    volumes:
      - ../src/backend/configs/apiv2.yaml:/etc/caliopen/apiv2.yaml
      - ../src/backend/configs/swagger.json:/etc/caliopen/swagger.json

  # Caliopen APIv1
  apiv1:
    image: public-registry.caliopen.org/caliopen_apiv1:develop
    depends_on:
      - redis
      - cassandra
      - elasticsearch
    expose:
      - "6543"
    volumes:
      - ../src/backend/configs/apiv1.ini:/etc/caliopen/apiv1.ini
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml
      - ../src/backend/configs/swagger.json:/etc/caliopen/swagger.json

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    expose:
      - "6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    expose:
      - "9042"
      - "9160"
      - "7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: elasticsearch:5-alpine
    expose:
      - "9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    image: public-registry.caliopen.org/caliopen_cli:develop
    depends_on:
      - cassandra
      - elasticsearch
      - lmtpd
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # Caliopen frontend
  frontend:
    image: public-registry.caliopen.org/caliopen_frontend:develop
    depends_on:
      - proxyapi
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      CALIOPEN_API_HOSTNAME: proxy-api

  # Broker
  lmtpd:
    image: public-registry.caliopen.org/caliopen_lmtpd:develop
    depends_on:
      - cassandra
      - elasticsearch
      - objectstore
      - nats
      - mqworker
    ports:
      - "127.0.0.1:2525:2525"
    volumes:
      - ../src/backend/configs/lmtp.yaml:/etc/caliopen/lmtp.yaml

  # NATS
  nats:
    image: nats:1.4.0
    expose:
      - "4222"

  # NATS Message Handler
  mqworker:
    image: public-registry.caliopen.org/caliopen_mq_worker:develop
    depends_on:
      - cassandra
      - elasticsearch
      - nats
    volumes:
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # object storage
  objectstore:
    image: minio/minio:latest
    expose:
      - "9090"
    volumes:
      - ../src/backend/configs/minio:/etc/caliopen/minio
      - store:/export
    command:
      server --address :9090 -C /etc/caliopen/minio /export

  # Worker for remote identities
  imapworker:
    image: public-registry.caliopen.org/caliopen_imap_worker:develop
    depends_on:
      - cassandra
      - objectstore
      - elasticsearch
      - nats
    volumes:
      - ../src/backend/configs/imapworker.yaml:/etc/caliopen/imapworker.yaml
    environment:
      - MINIO_ACCESS_KEY=CALIOPEN_ACCESS_KEY_
      - MINIO_SECRET_KEY=CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD

  twitterworker:
    image: public-registry.caliopen.org/caliopen_twitter_worker:develop
    depends_on:
    - cassandra
    - objectstore
    - elasticsearch
    - nats
    volumes:
    - ../src/backend/configs/twitterworker.yaml:/etc/caliopen/twitterworker.yaml

  # Poller for remote identities
  identitypoller:
    image: public-registry.caliopen.org/caliopen_identity_poller:develop
    depends_on:
      - imapworker
      - twitterworker
      - cassandra
      - nats
    volumes:
      - ../src/backend/configs/idpoller.yaml:/etc/caliopen/idpoller.yaml


  # Postfix : a complete smpt server that act as the Caliopen's MTA
  # TODO
