version: '2.1'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local

services:
  # Caliopen APIv2
  api:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-api
    image: api
    ## this very bad config for a public machine
    network_mode: "host"
    extra_hosts:
      - "apiv1.dev.caliopen.org:127.0.0.1"
      - "redis.dev.caliopen.org:127.0.0.1"
      - "cassandra.dev.caliopen.org:127.0.0.1"
      - "nats.dev.caliopen.org:127.0.0.1"
      - "es.dev.caliopen.org:127.0.0.1"
      - "minio.dev.caliopen.org:127.0.0.1"
    ports:
      - "31415:31415"
    volumes: 
      - ../src/backend/configs/apiv2.yaml:/etc/caliopen/apiv2.yaml
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml
  # Caliopen APIv1
  apiv1:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.py-api
    image: apiv1
    links:
      - redis:redis.dev.caliopen.org
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
    ports:
      - "6543:6543"
    volumes:
      - ../src/backend/configs/caliopen-api-development.ini:/etc/caliopen/caliopen-api-development.ini
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml
      - ../src/backend/configs/swagger.json:/etc/caliopen/swagger.json

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    ports:
        - "6379:6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.cli
    image: cli
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - broker:broker.dev.caliopen.org
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # Caliopen frontend
  frontend:
    build:
      context: ../src/frontend/web_application
    image: frontend
    network_mode: "host"
    ports:
      - "4000:4000"
    extra_hosts:
      - "api.dev.caliopen.org:127.0.0.1"

  # Broker
  broker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.go-lmtp
    image: broker
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - object_store:minio.dev.caliopen.org
      - nats:nats.dev.caliopen.org
      - message_handler:mc.dev.caliopen.org
      - inbucket:smtp.dev.caliopen.org
    ports:
      - "2525:2525"
    volumes:
      - ../src/backend/configs/lmtp.yaml:/etc/caliopen/lmtp.yaml

  # NATS
  nats:
    image: nats:0.9.6
    ports:
      - "4222:4222"

  # NATS Message Handler
  message_handler:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.message_handler
    image: message_handler
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - nats:nats.dev.caliopen.org

  # object storage
  object_store:
    image: minio/minio
    ports:
      - "9090:9090"
    volumes:
      - ../src/backend/configs/minio:/etc/caliopen/minio
      - store:/export
    command:
      server --address :9090 -C /etc/caliopen/minio /export

  # Worker for remote identities
  identity_worker:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.identity-worker
    image: identity_worker
    links:
      - cassandra:cassandra.dev.caliopen.org
      - object_store:minio.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - nats:nats.dev.caliopen.org
    volumes:
      - ../src/backend/configs/caliopen-imap-worker.yaml:/etc/caliopen/caliopen-imap-worker.yaml

  # Poller for remote identities
  identity_poller:
    build:
      context: ../src/backend
      dockerfile: Dockerfile.identity-poller
    image: identity_poller
    links:
      - identity_worker:identityworker.dev.caliopen.org
      - cassandra:cassandra.dev.caliopen.org
      - nats:nats.dev.caliopen.org
    volumes:
      - ../src/backend/configs/caliopen-IDs-poller.yaml:/etc/caliopen/caliopen-IDs-poller.yaml

  # Inbucket : a small smtp server to catch all outgoing emails for testing purpose
  # point your browser at localhost:8888
  inbucket:
    image: jhillyerd/inbucket
    ports:
      - "8888:9000"
