version: '2.1'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local
services:
  # Proxy API
  proxy-api:
    image: nginx
    links:
      - apiv2:apiv2
      - apiv1:apiv1
    expose:
      - "31415"
    volumes:
      - ./conf/proxy-api.conf:/etc/nginx/nginx.conf
  # Caliopen APIv2
  apiv2:
    image: public-registry.caliopen.org/caliopen_apiv2:develop
    links:
      - redis:redis
      - cassandra:cassandra
      - nats:nats
      - elasticsearch:es
      - object-store:minio
    expose:
      - "6544"
    volumes:
      - ../src/backend/configs/apiv2.yaml:/etc/caliopen/apiv2.yaml
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # Caliopen APIv1
  apiv1:
    image: public-registry.caliopen.org/caliopen_apiv1:develop
    links:
      - redis:redis
      - cassandra:cassandra
      - elasticsearch:es
    expose:
      - "6543"
    volumes:
      - ../src/backend/configs/apiv1.ini:/etc/caliopen/apiv1.ini
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml
      - ../src/backend/configs/swagger.json:/etc/caliopen/swagger.json

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    expose:
      - "6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    expose:
      - "9042"
      - "9160"
      - "7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    expose:
      - "9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    image: public-registry.caliopen.org/caliopen_cli:develop
    links:
      - cassandra:cassandra
      - elasticsearch:es
      - lmtpd:lmtpd
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # Caliopen frontend
  frontend:
    image: public-registry.caliopen.org/caliopen_frontend:develop
    links:
      - proxy-api:api
    ports:
      - "127.0.0.1:4000:4000"

  # Broker
  lmtpd:
    image: public-registry.caliopen.org/caliopen_lmtpd:develop
    links:
      - cassandra:cassandra
      - elasticsearch:es
      - object-store:minio
      - nats:nats
      - mq-worker:mc
    ports:
      - "127.0.0.1:2525:2525"
    volumes:
      - ../src/backend/configs/lmtp.yaml:/etc/caliopen/lmtp.yaml

  # NATS
  nats:
    image: nats:0.9.6
    expose:
      - "4222"

  # NATS Message Handler
  mq-worker:
    image: public-registry.caliopen.org/caliopen_mq_worker:develop
    links:
      - cassandra:cassandra
      - elasticsearch:es
      - nats:nats
    volumes:
      - ../src/backend/configs/caliopen.yaml:/etc/caliopen/caliopen.yaml

  # object storage
  object-store:
    image: minio/minio
    expose:
      - "9090"
    volumes:
      - ../src/backend/configs/minio:/etc/caliopen/minio
      - store:/export
    command:
      server --address :9090 -C /etc/caliopen/minio /export

  # Worker for remote identities
  imap-worker:
    image: public-registry.caliopen.org/caliopen_imap_worker:develop
    links:
      - cassandra:cassandra
      - object-store:minio
      - elasticsearch:es
      - nats:nats
    volumes:
      - ../src/backend/configs/imapworker.yaml:/etc/caliopen/imapworker.yaml
    environment:
      - MINIO_ACCESS_KEY=CALIOPEN_ACCESS_KEY_
      - MINIO_SECRET_KEY=CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD

  twitter-worker:
    image: public-registry.caliopen.org/caliopen_twitterworker:develop
    links:
    - cassandra:cassandra
    - object-store:minio
    - elasticsearch:elasticsearch
    - nats:nats
    volumes:
    - ../src/backend/configs/twitterworker.yaml:/etc/caliopen/twitterworker.yaml

  # Poller for remote identities
  identity-poller:
    image: public-registry.caliopen.org/caliopen_identity_poller:develop
    links:
      - imap-worker:imap-worker
      - twitter-worker:twitter-worker
      - cassandra:cassandra
      - nats:nats
    volumes:
      - ../src/backend/configs/idpoller.yaml:/etc/caliopen/idpoller.yaml


  # Postfix : a complete smpt server that act as the Caliopen's MTA
  # TODO
