apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-handler
  template:
    metadata:
      labels:
        type: message-handler
        tier: backend
        app: message-handler
    spec:
      containers:     
      - image: registry.caliopen.org:5043/message-handler
        name: message-handler
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml
      restartPolicy: Always