apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-worker
  template:
    metadata:
      labels:
        type: mq-worker
        tier: backend
        app: mq-worker
    spec:
      containers:
      - image: public-registry.caliopen.org/caliopen_mq_worker:develop
        imagePullPolicy: Always
        name: mq-worker
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml
